server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ssm_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait: 30000


